version: 2
jobs:
  create-tar:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install ruby dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependency-cache-

      - run:
          name: install npm dependencies
          command: |
            npm install

      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: create tar 
          command: |
            make create-tar
            mkdir -p /tmp/workspace
            mv black-knight.tar /tmp/workspace/black-knight.tar

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - black-knight.tar
        
      - store_artifacts:
          path: /tmp/workspace/black-knight.tar
          destination: black-knight.tar

  upload-artifact:
    machine: true

    steps:
      - run: 
          name: Install aws cli
          command: pip install awscli
      - run:
          name: upload artifact
          command: make upload-artifact

      - attach_workspace:
          at: /tmp/workspace

workflows:
  version: 2
  pipeline:
    jobs:
      - create-tar
      - upload-artifact:
          requires:
            - create-tar
          context: artifacts
