development:
  paths: ['/app/log/development.log', '/app/storage/logs/laravel.log', '/var/log/nginx/error.log', stdout]

production:
  paths: ['/app/log/production.log', '/app/storage/logs/laravel.log', '/var/log/nginx/error.log', stdout]
